### ISSUE TITLE
Listar todas as mudanças em forma de histórico

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/catalogmanager#5]
Para atender os processamentos em lote, informando quais as mudanças ocorridas a partir de um determinado marco, mantendo a ordem em que elas ocorreram e garantir que nenhuma mudança seja informada, é necessária uma lista sequencial de todas as mudanças.
Para que as mudanças já processadas não sejam re-processadas, a informação da última sequência processada é importante. Também é relevante poder informar o número máximo de mudanças que o processamento vai receber.
Além disso, identificar em que nível a mudança ocorreu: dados de periódicos, fascículos, artigo ou ativos.

Tarefas relacionadas:
- [x] #86 - Listar histórico de mudanças na API
- [x] #89 - Identificação sequencial para as mudanças

**Comment by gustavofonseca** [comment]
@patymori, acho que vc poderia descrever aqui a especificação que fizemos ontem para a funcionalidade de histórico de mudanças e relacionar todas as tarefas. O que acha?

**Comment by patymori** [comment]
@gustavofonseca, relacionei as tarefas nesta issue, que imaginei manter somente com o descritivo da funcionalidade de negócio macro. Os detalhes do que cada uma das tarefas precisa atender estão no descritivo das respectivas issues. Acha que assim fica ruim ou sentiu falta de alguma coisa aqui?

**Comment by gustavofonseca** [comment]
Acho que tivemos um problema de corrida. Quando eu comentei vc ainda não havia realizado a alteração na descrição do ticket. Agora está ok. Valeu.
