### ISSUE TITLE
Alterar Catalog Manager API para dividir e reorganizar os resources

### ISSUE THREAD

**Issue by patymori** [scieloorg/catalogmanager#67]
As URLs de Artigo estão definidas em uma mesma classe com um Cornice resource e adição de rotas de URL dispatch. É necessário reorganizar as URLs em 3 resources diferentes:

- /articles/{id}, para registrar/recuperar metadados do documento do artigo
- /articles/{id}/xml, para recuperar XML do artigo
- /articles/{id}/asset/{id_asset}, para recuperar ativo digital do artigo

Por ter a terceira parte da URL como variável ou fixa, pode acarretar em problema na identificação da view que responderá à requisição (Ex. {id_asset} pode ser xml). Então, definir a terceira parte como fixa é uma opção.

Detalhes sobre utilização do Cornice:
https://cornice.readthedocs.io/en/latest/resources.html

**Comment by gustavofonseca** [comment]
Acho que podemos resolver esse problema sem mudar a estratégia de resolução das URLs para traversal. Esperem eu fazer uns testes com o Cornice antes de implementar qqer coisa nesse ticket, ok?
