### ISSUE TITLE
Carga de pacotes de XML e ativos digitais em uma instância no Rancher

### ISSUE THREAD

**Issue by patymori** [scieloorg/catalogmanager#72]
Carregar pacotes de artigos XML e ativos digitais reais em servidor.

**Comment by gustavofonseca** [comment]
Este ticket está "in review", mas qual seu real status? O que foi feito e quais os resultados?

**Comment by patymori** [comment]
@gustavofonseca Coloquei ele em review pois precisamos definir se ele está OK ou não para fechar. @robertatakenaka fez os testes com a carga de artigos e criou tickets de bug relacionados aos problemas encontrados.

**Comment by patymori** [comment]
Acrescentando:
- Configuração do container no Rancher

**Comment by patymori** [comment]
@robertatakenaka , fica pendente para essa issue:

- Complementar a descrição das atividades desenvolvidas nessa tarefa
- Descrever os casos de testes executados (Ex.: XML sem ativos, XML com ativos com mais de 1 GB de tamanho, XML com grande quantidade de ativos digitais etc.).
- Resultado dos casos de testes (Ex.: pacotes de artigos carregados com sucesso, erros identificados, melhorias a serem feitas)

**Comment by robertatakenaka** [comment]
- Criada a imagem do catalogmanager no hubdocker
- Criada uma instância no Rancher
- Uso de alguns pacotes aleatórios do SciELO Brasil (fascículos 1 de cada ano de todos os periódicos)  

http://192.168.1.149:6543 (webapp)
http://192.168.1.148:5984 (couchdb)
http://192.168.1.148:5984/_utils/#/_all_dbs

- Verificou-se a necessidade de correções, tickets criados:
  - #80
  - #81
  - #82 
  - #83 
- Foi detectado que alguns arquivos deram erro de timeout na carga provavelmente devido a quantidade grande de ativos digitais (cerca de 30). Estes mesmos pacotes foram carregados com sucesso quando feitos no servidor local (fora do Rancher) 
- Também verificou-se necessidade de melhorias nas assinaturas de ArticleService->receive_asset_file e ArticleService->receive_asset_files e também melhoria nos retornos de receive_xml_file, receive_asset_file e receive_asset_files, pois não fica explícito se foi ou não bem sucedido o registro dos dados. 

No entanto, devemos fazer as correções no momento em que for modificada a interface da API para considerar:
   - o versionamento dos XML e dos ativos digitais;
   - a carga individuais de ativos digitais;

**Comment by robertatakenaka** [comment]
@gustavofonseca podemos considerar fechado?

**Comment by gustavofonseca** [comment]
@robertatakenaka, sim.
