### ISSUE TITLE
Retornar na api o resultado do registro do pacote

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/catalogmanager#81]
- retornar se há arquivos faltantes
- retornar se há arquivos a mais
- retornar falhas se aplicável

**Comment by gustavofonseca** [comment]
@patymori, penso que este ticket trata de uma melhoria e não um bug. O que acha?

**Comment by patymori** [comment]
@gustavofonseca e @robertatakenaka , esta issue diz respeito a funcionalidade de Registrar XML (feature #2 ). Como esses retornos não foram especificados na funcionalidade, eles podem ser encarados como uma melhoria ou como uma nova funcionalidade no que diz respeito a uma nova entrega de valor.
Na prática e nesse momento, qualquer uma das escolhas dá no mesmo.

**Comment by patymori** [comment]
Conforme conversado, é necessário dividir o registro de Artigos do registro de ativos digitais em dois serviços separados. Com isso, o serviço de registro de pacotes não deveria existir e é necessário definir esse retorno em outro serviço.

**Comment by gustavofonseca** [comment]
Este ticket está sendo fechado por ter sido considerado inválido.
