### ISSUE TITLE
Implementar identificação Sequencial para as mudanças

### ISSUE THREAD

**Issue by patymori** [scieloorg/catalogmanager#89]
Para garantir que mantenha-se a ordem sequencial das mudanças registradas, é necessário criar um identificador sequencial para cada mudança. É importante se atentar a como esse identificador sequencial será gerado e gerenciado, pois deve ser um identificador único recebendo requisições simultaneamente. Uma sugestão é a implementação de gerenciamento transacional e o formato deverá ser algo como `SEQ + <número sequencial>`

Related to #5

**Comment by gustavofonseca** [comment]
Eu diria que o prefixo _SEQ_ não é necessário, mas apenas o número inteiro.
