### ISSUE TITLE
InMemoryDBManager.find() não ordena sem especificação de filtro de seleção

### ISSUE THREAD

**Issue by patymori** [scieloorg/catalogmanager#92]
`InMemoryDBManager.find()` considera o parâmetro de entrada `sort` somente se `filter` tiver algo definido.

Exemplo: Caso seja solicitada uma busca de todos os registros de documentos ordenados por data de criação, a consulta retorna todos na ordem de iteração do dicionário onde é armazenado.

**Comment by gustavofonseca** [comment]
Essa é uma péssima prática em design de APIs. Nunca devemos criar dependências transitivas entre argumentos de uma função ou método, sob pena de criarmos APIs imprevisíveis e programas com bugs super difíceis de rastrear.

**Comment by patymori** [comment]
Closed by #104
